msclvr/config/routes.rb
Msclvr::Application.routes.draw do
  root to: "home#index"

  devise_for :affiliates
  resources :msclvrs, controller: "affiliates"
  resources :promotions
  resources :songs
  resources :dashboards

  resources :links
 
  get ":slug" => "promotions#go"
 
  
  devise_scope :affiliate do
    get "msclvrs/new" => "devise/registrations#new"
  end

  devise_scope :affiliate do
    get "/login" => "devise/sessions#new"
  end

  devise_scope :affiliate do
    delete "/logout" => "devise/sessions#destroy"
  end
  
  

end

msclvr/app/models/promotion.rb
class Promotion < ActiveRecord::Base
  attr_accessible :affiliate_id, :song_id, :track_url, :slug, :short_url, :short_url2, :custom_ending

  # validates :short_url2, :uniqueness => true


  # ----- we only want to save the slug once to the database
  # if we did not do this the slug would either never save or 
  # it would regenerate every time the promotion was updated 
  
  before_create :generate_slug
  # before_update :customize_redirect_link

  # -----

  belongs_to :affiliate
  belongs_to :song
  
  

  def set_track_url
  end



  private
  @url_head = "localhost:3000/"

  def generate_slug
    self.slug = SecureRandom.hex(3)
    # redirect_link = @url_head + slug
    self.short_url = "www.msclvr.com/" + slug.to_s
  end
  
# ----- http://rails-bestpractices.com/posts/47-fetch-current-user-in-models

  # def self.current
  #   Thread.current[:promotion]
  # end

  # def self.current=(promotion)
  #   Thread.current[:promotion] = promotion
  # end

 
end

msclvr/app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
	
	def go
		promotion = Promotion.find_by_slug!(params[:slug])	
		redirect_to promotion.track_url

		# if Promotion.find_by_custom_ending(params[:custom_ending]).nil?
		# 	promotion = Promotion.find_by_slug(params[:slug])
		# 	redirect_to promotion.track_url
		# else 
		# 	promotion = Promotion.find_by_custom_ending(params[:custom_ending])
		# 	redirect_to promotion.track_url
		# end
	end

	def index
		@promotions = current_affiliate.promotions

		respond_to do |format|
			format.html #show.html.erb
			format.json { render json: @promotions }
		end
	end

	def show
		@promotion = Promotion.find(params[:id])

		respond_to do |format|
			format.html #show.html.erb
			format.json { render json: @promotion }
		end
	end

	def new
		@promotion = current_affiliate.promotions.build
		@allsongs = Song.all

		respond_to do |format|
      		format.html # new.html.erb
      		format.json { render json: @promotion }
      	end
	end

# ----- GET /promotions/1/edit
  	def edit
    	@promotion = Promotion.find(params[:id])
    	@allsongs = Song.all
  	end

 	def create
 		@promotion = current_affiliate.promotions.build(params[:promotion])
 		@promotion.track_url = Song.find(@promotion.song_id).track_url
 		@allsongs = Song.all
 		
 		# customize_redirect_link
 		

 		if @promotion.save
 			redirect_to @promotion, notice: 'Promotion was successfully created.'
        	#format.json { render json: @link, status: :created, location: @link }
      	else
        	render action: "new" 
        	#format.json { render json: @link.errors, status: :unprocessable_entity }
      	end
 	end

 	def update
 		@promotion = Promotion.find(params[:id])

 		if @promotion.update_attributes(params[:promotion])
 			redirect_to @promotion, notice: 'Promotion was successfully updated.'
 		else
 			render action: "edit"
 		end
 	end

 	def destroy
 		@promotion = Promotion.find(params[:id])
 		@promotion.destroy

 		respond_to do |format|
      		format.html { redirect_to promotions_url }
      		format.json { head :no_content }
 		end
 	end


end

msclvr/app/helpers/promotion_helper.rb
module PromotionHelper
end

msclvr/app/views/promotions/_form.html.erb
<%= form_for(@promotion) do |f| %>
  <% if @promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
      <% @promotion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :track_name, "Find your song below:" %>
    <%= f.collection_select :song_id, @allsongs, :id, :track_name, :prompt => "- Select Track -" %>
  </div>

  <div class="field">
    <%= f.label :custom_ending, "Custom Ending?" %>
    <%= f.text_field :custom_ending %>
  </div>

  <div class="actions">
    <%= f.submit "DO IT!", :style =>'color: #FFFFFF',:class => 'btn btn-large btn-info'  %>
  </div>


<% end %>

msclvr/app/views/promotions/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

msclvr/app/views/promotions/index.html.erb
<h1><%= current_affiliate.username.capitalize %>'s Promotions</h1>

<div width="500">
  <table width="100" border= "1" cellpadding= "5">
    <tr>
      <th>Promotion ID</th>
      <th>Song Name</th>
      <th>Slug</th>
      <th>Link To Share</th>
      <th>Track Url</th>
      <th>Username</th>
      <th>Custom Ending</th>
      <th>Edit</th>
    </tr>
    <% @promotions.each do |promotion| %>
    <tr>
      <td><%= promotion.id %></td>
      <td><%= promotion.song.track_name %></td>
      <td><%= promotion.slug %></td>
      <td><%= promotion.short_url %></td>
      <td><%= promotion.track_url %></td>
      <td><%= promotion.affiliate.username.capitalize %></td>
      <td><%= promotion.custom_ending %></td>
      <td><%= link_to 'Edit', edit_promotion_path(promotion) %></td>
      <!-- <td><%#= link_to 'Show', link %></td>
      <td><%#= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>  -->
    </tr>
    <% end %>
  </table>
</div>

<br/>

<%= link_to 'New Promotion', new_promotion_path %>

msclvr/app/views/promotions/new.html.erb
<h1>What Song Are We Promoting?</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

msclvr/app/views/promotions/show.html.erb
<p id="notice"><%= notice %></p>


<div width="500">
	<table cellpadding="5" border="1" width="500">
		<tr>
			<th>Promotion:</th>
			<th>Song:</th>
			<th>URL:</th>
			<th>Custom Ending:</th>
			<th>Slug:</th>
			<th>Edit:</th>
		</tr>
		<tr>
			<td> <%= @promotion.id %> </td>
			<td> <%= Song.find(@promotion.song_id).track_name %> </td>
			<td> <%= @promotion.track_url %> </td>
			<td> <%= @promotion.custom_ending %> </td>
			<td> <%= @promotion.slug %> </td>
			<td> <%= link_to 'edit', edit_promotion_path(@promotion) %> </td>
		</tr>	
	</table>
</div>
</br>
<%= link_to 'New Promotion', new_promotion_path %> |
<%= link_to 'Edit', edit_promotion_path(@promotion) %> |
<%= link_to 'Back', promotions_path %> |
<%= link_to 'My Promotions', promotions_path %> |